### ISSUE TITLE
Remove props from component when AutoProps change prop to undefined

### ISSUE THREAD

**Issue by allyssonsantos** [catho/quantum-storybook-ui#6]
In some cases it's important to remove props from the rendered component on preview panel.

Example:

![toggle-error](https://user-images.githubusercontent.com/13424727/53165876-94e50a80-35b2-11e9-8eb2-af30f2e43b69.gif)

- On first render component have checked value equals `undefined`, so, its an `uncontrolled` component;
- When checked is defined, the component on preview panel and on the code example receive `true` as a value, and, the component is now `controlled`;
- When checked prop is removed the component on preview panel receive `false` but on code example panel the props is `undefined`, because its not present on code example, in this case, the component must receive `undefined` to be uncontrolled again.

So, we need to remove props (set as undefined) from the rendered component on preview panel.

**Comment by alan-oliv** [comment]
Same as https://github.com/catho/quantum-storybook-ui/issues/7
Resolved issue
